const highway_services = [
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B023500W3M",
          name: "福山服务区(芜合高速芜湖方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.026435, 31.580622],
          address: "含山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023404LN1",
          name: "西桥服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.444781, 31.849327],
          address: "裕安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022603WJN",
          name: "吴圩服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.446731, 32.372283],
          address: "定远县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG640U3",
          name: "香铺服务区(合安高速合肥方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.937236, 30.908149],
          address: "桐城市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFRME",
          name: "皇甫山服务区(滁新高速新蔡方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.989182, 32.28821],
          address: "南谯区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFVO9",
          name: "大墅服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.926369, 32.005383],
          address: "全椒县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIP2YYY",
          name: "全椒服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.197706, 32.08361],
          address: "全椒县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023404YCB",
          name: "霍山服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.404036, 31.455863],
          address: "霍山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023500YDF",
          name: "陈埠服务区(合安高速合肥方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.161097, 31.218591],
          address: "庐江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8DE",
          name: "文集服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.717168, 31.957776],
          address: "肥东县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 3,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B022C03OZ6",
          name: "香铺服务区(合安高速安庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.935569, 30.909392],
          address: "桐城市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0234047GL",
          name: "西桥服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.443322, 31.850788],
          address: "裕安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270IHEI",
          name: "肥东服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.455107, 31.85431],
          address: "肥东县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270JS7P",
          name: "众兴服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.418495, 31.976225],
          address: "肥东县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHXLBJ4",
          name: "清溪服务区(沪武高速武汉方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.017399, 31.635169],
          address: "含山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270IAQD",
          name: "新桥服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.894194, 31.918472],
          address: "蜀山区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023500YDE",
          name: "陈埠服务区(合安高速安庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.159506, 31.220147],
          address: "庐江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIP2Z1M",
          name: "全椒服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.199006, 32.081866],
          address: "全椒县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022603WIC",
          name: "吴圩服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.449101, 32.371993],
          address: "吴圩镇",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8CD",
          name: "文集服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.71759, 31.959598],
          address: "沪陕高速附近",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 2,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFHI4W7V",
          name: "天堂寨停车区(沪蓉高速成都方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.728636, 31.457726],
          address: "沪蓉高速",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02340TZB3",
          name: "徐集服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.359252, 31.816885],
          address: "裕安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02340TZYY",
          name: "河口服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.075998, 32.144363],
          address: "霍邱县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFFSXI0I",
          name: "宁国服务区(溧宁高速宁德方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.006098, 30.550273],
          address: "宁国市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023404YBT",
          name: "梅山服务区(沪蓉高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.013964, 31.754517],
          address: "金寨县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022A02BWC",
          name: "八公山服务区(滁新高速新蔡方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.965476, 32.544769],
          address: "谢家集区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022603YPE",
          name: "嘉山服务区(宁洛高速南京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.24868, 32.535176],
          address: "明光市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022E02G1W",
          name: "辛集服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.859406, 33.849941],
          address: "谯城区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIHFIZB",
          name: "长春服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.892321, 33.294001],
          address: "太和县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG6RRUF",
          name: "蒙城服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.419293, 33.02037],
          address: "蒙城县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 6,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B02270IHEH",
          name: "肥东服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.455587, 31.856856],
          address: "肥东县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAMQ70018",
          name: "巢湖服务区(芜合高速合肥方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.805398, 31.760016],
          address: "巢湖市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I1E9",
          name: "新桥服务区(沪陕高速西安方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.894171, 31.9203],
          address: "蜀山区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIU127H",
          name: "巢湖服务区(芜合高速芜湖方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.803501, 31.758624],
          address: "巢湖市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8SN",
          name: "丰乐服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.183981, 31.59423],
          address: "肥西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270IAQG",
          name: "众兴服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.417218, 31.97382],
          address: "肥东县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022A02BHH",
          name: "八公山服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.964864, 32.543068],
          address: "谢家集区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8X9",
          name: "丰乐服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.186442, 31.593967],
          address: "肥西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFINHLMJ",
          name: "清溪服务区(沪武高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.018239, 31.634136],
          address: "含山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8U2",
          name: "龙门寺服务区(蚌合高速合肥方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.103659, 32.139139],
          address: "长丰县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 1,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "BZAKPZ0016",
          name: "小井庄服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.793745, 31.624863],
          address: "肥西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022D02OCP",
          name: "符离服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.936207, 33.729117],
          address: "埇桥区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C04040",
          name: "潜山服务区(济广高速广州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.509841, 30.623051],
          address: "潜山市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG6DLYH",
          name: "大溪河服务区(宁洛高速洛阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.80251, 32.893906],
          address: "凤阳县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHH5AWC",
          name: "仓头服务区(巢黄高速巢湖方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.954205, 31.377991],
          address: "无为市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG3EKKF",
          name: "岳西服务区(济广高速广州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.320378, 30.89467],
          address: "岳西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C02UPC",
          name: "公岭服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.739169, 30.688902],
          address: "怀宁县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZACPZ0003",
          name: "青草服务区(沪武高速武汉方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.82331, 30.911402],
          address: "桐城市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAGPZ0015",
          name: "万佛湖服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.866449, 31.302179],
          address: "舒城县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHCYK7S",
          name: "新芜服务区(溧芜高速芜湖方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.609864, 31.275806],
          address: "湾沚区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 5,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFIKFO6X",
          name: "杜集服务区(滁新高速新蔡方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.301882, 32.398295],
          address: "长丰县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZATQ60004",
          name: "仓镇服务区(滁新高速新蔡方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.741565, 32.390325],
          address: "定远县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFFSXI48",
          name: "桥头服务区(徐明高速明光方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.945153, 32.935313],
          address: "明光市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIY6B6D",
          name: "水东服务区(宣桐高速宣城方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.953578, 30.769],
          address: "宣州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGK38MD",
          name: "中溪服务区(宣桐高速宣城方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.124925, 30.507865],
          address: "宁国市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B06160RCE2",
          name: "阜南服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.647916, 32.789255],
          address: "颍州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C03G78",
          name: "王河服务区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.544613, 30.569713],
          address: "王河镇",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0228017MM",
          name: "君王服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.0541, 33.263215],
          address: "怀远县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02270I8U3",
          name: "龙门寺服务区(蚌合高速蚌埠方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.105853, 32.138949],
          address: "长丰县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C01FJB",
          name: "宿松服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.114024, 30.179152],
          address: "孚玉镇",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 4,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFHOAMFN",
          name: "石涧服务区(沪武高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.920579, 31.47363],
          address: "无为市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGIFPJ8",
          name: "伍明服务区(济广高速广州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.897002, 33.044393],
          address: "济广高速东王营路段",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022D03M44",
          name: "宿州服务区(盐洛高速洛阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.058375, 33.70931],
          address: "埇桥区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C05WBY",
          name: "大龙山服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.011702, 30.63025],
          address: "宜秀区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAGQ40009",
          name: "庐江东服务区(沪武高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.417471, 31.333042],
          address: "庐江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02320187E",
          name: "顺安停车区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.964716, 30.927808],
          address: "义安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHUKVMA",
          name: "呈坎服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.285451, 29.934831],
          address: "徽州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZABPV002U",
          name: "温泉服务区(沪武高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.359926, 30.875674],
          address: "岳西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAGPZ0014",
          name: "万佛湖服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.868359, 31.300959],
          address: "舒城县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023600JJ4",
          name: "升金湖服务区(安东高速安庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.966368, 30.346553],
          address: "东至县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 7,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFF01HWV",
          name: "齐云山服务区(黄浮高速浮梁方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.137487, 29.751423],
          address: "休宁县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFUWZ",
          name: "大墅服务区(沪陕高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.926714, 32.003479],
          address: "全椒县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022F00F3A",
          name: "太平湖停车区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.980885, 30.320195],
          address: "黄山区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGK38LM",
          name: "中溪服务区(宣桐高速桐庐方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.125167, 30.506046],
          address: "宁国市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02330NO66",
          name: "华阳服务区(溧宁高速溧阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.544888, 30.061207],
          address: "绩溪县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG4T7A8",
          name: "林东半岛服务区(宁洛高速洛阳方向)(建设中)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.166872, 32.666983],
          address: "明光市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFO3E",
          name: "皇甫山服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.98845, 32.286706],
          address: "南谯区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B06160RCE3",
          name: "阜南服务区(滁新高速新蔡方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.64813, 32.79059],
          address: "颍州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHSYRHS",
          name: "金沙服务区(溧宁高速宁德方向)",
          type: "道路附属设施;服务区;高速加油站服务区",
          location: [118.754673, 30.287407],
          address: "绩溪县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGLW1NM",
          name: "马集服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.355305, 33.324545],
          address: "蒙城县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 12,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFGEQWXE",
          name: "滁州服务区(天天高速天长方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.380099, 32.20183],
          address: "南谯区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHNWVGI",
          name: "茶庵服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.781346, 32.053589],
          address: "寿县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZARQA000Q",
          name: "石沛服务区",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.154196, 32.191125],
          address: "全椒县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023404YCC",
          name: "霍山服务区(济广高速广州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.402137, 31.45533],
          address: "霍山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGKSA3J",
          name: "服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.751073, 30.848043],
          address: "郊区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02290HZR1",
          name: "新竹服务区(芜合高速合肥方向)(建设中)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.595596, 31.210407],
          address: "湾沚区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAWQF001L",
          name: "天长西服务区(天天高速天长方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.81319, 32.612471],
          address: "天长市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAHQ4000T",
          name: "庐江东服务区(沪武高速武汉方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.416303, 31.334202],
          address: "庐江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02290IA34",
          name: "千军服务区(宁芜高速南京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.273662, 31.090115],
          address: "繁昌区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02260QQCD",
          name: "官塘服务区(蚌合高速蚌埠方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.25827, 32.697387],
          address: "凤阳县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 10,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B023600GM1",
          name: "马衙服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.589667, 30.647572],
          address: "贵池区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKGEF7",
          name: "冯庙服务区(徐明高速徐州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.690691, 33.687545],
          address: "灵璧县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFFSU7TJ",
          name: "桥头服务区(徐明高速徐州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.946934, 32.935176],
          address: "明光市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0232017W0",
          name: "天门服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.818584, 30.827407],
          address: "义安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHOAMPB",
          name: "石涧服务区(沪武高速武汉方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.919679, 31.475529],
          address: "无为市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAXQ7000F",
          name: "梅市服务区(明合高速明光方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.879041, 32.681328],
          address: "凤阳县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFN2V",
          name: "五河服务区(泗蚌高速蚌埠方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.726868, 33.066665],
          address: "五河县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFRKF",
          name: "仓镇服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.739991, 32.389298],
          address: "定远县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C03PFU",
          name: "周潭服务区(京台高速北京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.555537, 30.882632],
          address: "郊区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHWGQPS",
          name: "马集服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.357313, 33.324548],
          address: "蒙城县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 11,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFFSXI47",
          name: "石龙湖服务区(徐明高速明光方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.833093, 33.300028],
          address: "泗县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022D03M4F",
          name: "虞姬服务区(盐洛高速盐城方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.591853, 33.595204],
          address: "灵璧县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZABPZ000J",
          name: "青草服务区(沪武高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.825665, 30.911467],
          address: "桐城市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIKFN94",
          name: "杜集服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.301782, 32.396538],
          address: "长丰县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02330OBYQ",
          name: "水东服务区(宣桐高速桐庐方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.951512, 30.768629],
          address: "宣州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023404YCJ",
          name: "长岭关服务区(沪蓉高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.48607, 31.303526],
          address: "金寨县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C05WDJ",
          name: "天柱山服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.498793, 30.654088],
          address: "潜山市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFFHVP73",
          name: "红星服务区(济广高速广州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.972757, 32.699121],
          address: "颍上县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGO6OB0",
          name: "砀山服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.410885, 34.465769],
          address: "砀山县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAKPZ0015",
          name: "小井庄服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.79206, 31.624099],
          address: "肥西县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 9,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFFSXI46",
          name: "石龙湖服务区(徐明高速徐州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.835048, 33.300215],
          address: "泗县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022A0NZW5",
          name: "焦岗湖服务区(滁新高速滁州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.660464, 32.620608],
          address: "凤台县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023600GM0",
          name: "马衙服务区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.588494, 30.648878],
          address: "贵池区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023300NKX",
          name: "广德服务区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.401906, 30.872449],
          address: "广德市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG7NV9W",
          name: "凤台服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.664515, 32.730952],
          address: "凤台县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHTR161",
          name: "望江服务区(济广高速济南方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.71445, 30.153123],
          address: "望江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B02310O56Y",
          name: "濉溪服务区(盐洛高速洛阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.713994, 33.750499],
          address: "濉溪县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023502FH9",
          name: "沙溪服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.251606, 31.14857],
          address: "庐江县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFFTBV84",
          name: "南陵服务区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.223156, 30.948331],
          address: "南陵县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0JUY5NFF5",
          name: "老洲镇服务区(京台高速台北方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.716096, 30.856863],
          address: "郊区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 8,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFI8F9YB",
          name: "芍陂服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.760295, 32.376891],
          address: "寿县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZA3QC000J",
          name: "旌德服务区(巢黄高速黄山方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.389839, 30.245937],
          address: "旌德县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022B00HJM",
          name: "太白服务区(宁芜高速南京方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.526104, 31.489067],
          address: "当涂县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFIMTDB1",
          name: "临泉服务区",
          type: "道路附属设施;服务区;高速服务区",
          location: [115.230938, 32.847524],
          address: "临泉县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG63WVA",
          name: "顺安停车区(沪渝高速上海方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.966226, 30.927082],
          address: "义安区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZ9ZQD001D",
          name: "深渡服务区(溧宁高速溧阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.616975, 29.872431],
          address: "歙县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHBRFOF",
          name: "南漪湖服务区",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.945707, 31.163971],
          address: "宣州区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZA2Q50005",
          name: "石台牯牛降服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.625173, 30.137381],
          address: "石台县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFG3DYKZ",
          name: "宁国服务区(溧宁高速溧阳方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.006944, 30.548884],
          address: "宁国市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZACQ2000I",
          name: "浮山服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.202779, 30.946477],
          address: "枞阳县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 14,
      pageSize: 10,
    },
  },
  {
    info: "OK",
    poiList: {
      pois: [
        {
          id: "B0FFIKFRCO",
          name: "五河服务区(泗蚌高速泗洪方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.72653, 33.064966],
          address: "五河县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZACQA001D",
          name: "南陵家发服务区(巢黄高速黄山方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.238896, 30.986392],
          address: "南陵县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022603YPH",
          name: "釜山服务区(长深高速长春方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.723327, 32.6349],
          address: "天长市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B023C02XZH",
          name: "界牌服务区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [119.564898, 30.916397],
          address: "广德市",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFGPT76P",
          name: "香隅服务区(东彭高速东至方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.805564, 30.012584],
          address: "东至县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B022C03PHA",
          name: "公岭服务区(沪渝高速重庆方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [116.738696, 30.689846],
          address: "怀宁县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZ9ZQ7000L",
          name: "柏溪服务区(德上高速上饶方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.794132, 29.907911],
          address: "祁门县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZA6Q3001F",
          name: "殷家汇服务区(德上高速德州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [117.375128, 30.420122],
          address: "贵池区",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "BZAUQC0031",
          name: "来安北服务区(天天高速天柱山方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.475767, 32.447427],
          address: "来安县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
        {
          id: "B0FFHTR181",
          name: "三阳服务区(杭瑞高速杭州方向)",
          type: "道路附属设施;服务区;高速服务区",
          location: [118.819156, 30.03279],
          address: "歙县",
          tel: "",
          distance: null,
          shopinfo: "2",
        },
      ],
      count: 339,
      pageIndex: 13,
      pageSize: 10,
    },
  },
];
